module PointerAnalyzer.Summary.FunctionSummaryBuilder

open B2R2
open B2R2.BinIR.SSA

open PointerAnalyzer.Platform.PlatformTypes
open PointerAnalyzer.Analysis.Analyzer
open PointerAnalyzer.Summary
open PointerAnalyzer.AbsDom.TypeConstraint
open PointerAnalyzer.AbsDom.TypeIdMap

module FunctionSummaryBuilder =
  /// Select the type id of the SSA variable satisfying given condition in each
  /// group. This is used for extracting the type id of parameters.
  let private selectByIdentifier
    identifierCond
    (entries: (int * Variable * TypeId) seq)
    : Map<int, TypeId> =
    let extractRegId (_paramIdx: int, reg, _tid: TypeId) = reg.Identifier

    let chooseReg (paramIdx: int, regSeq) =
      let _, _, typeId = identifierCond extractRegId regSeq
      paramIdx, typeId

    let sameParamIdxSeq = Seq.groupBy (fun (index, _, _) -> index) entries

    sameParamIdxSeq |> Seq.map chooseReg |> Map.ofSeq

  /// Merge return-register type IDs from all RETURN leaf states.
  /// `address` and `name` is information of target function.
  let private mergeReturnTypeIds address name trackOrigins groupedTypeIds =
    let mergeRegister
      (constraints_, origins_, returns_)
      (regId, typeIds: Set<TypeId>)
      =
      if Set.isEmpty typeIds then
        (* Nothing to merge *)
        constraints_, origins_, returns_
      else
        let representative = Set.minElement typeIds

        let constraints_, origins_ =
          if Set.count typeIds <= 1 then
            (* Nothing to merge *)
            constraints_, origins_
          else
            (* Merge returns *)
            let constraint_ = Same typeIds
            (* Record constraint generated by merging *)
            let origins_ =
              match origins_ with
              | Some origins ->
                Some (
                  Map.add
                    constraint_
                    { FunctionName = name
                      Location = "function summary"
                      Statement =
                        "Merge return-register types from CFG Return leaves"
                      Annotation = "Return Register Merge" }
                    origins
                )
              | None -> None

            Set.add constraint_ constraints_, origins_

        constraints_, origins_, Map.add regId representative returns_

    let initialOrigins = if trackOrigins then Some Map.empty else None

    groupedTypeIds
    |> Seq.fold mergeRegister (Set.empty, initialOrigins, Map.empty)

  /// Construct function summary for analyzing caller
  let build address name platform (result: AnalysisResult) =
    (* If given variable is parameter, then retrieve its parameter index *)
    let filterParams (reg, tid: TypeId) =
      match platform.TryParameterIndex reg with
      | Some paramIdx -> Some (paramIdx, reg, tid)
      | None -> None

    let typeIndSeq = result.FinalState.Types.TypeIndicators |> Map.toSeq

    (* Summarize parameter type information *)
    let paramIdxTidMap =
      typeIndSeq |> Seq.choose filterParams |> selectByIdentifier Seq.minBy

    (* Summarize ABI return registers from all leaf nodes. *)
    let returnRegisters = Set.ofList platform.ReturnRegisters

    let groupedReturnTypeIds =
      result.LeafStates
      |> Map.toSeq
      |> Seq.collect (fun (_, state) -> state.CurrentRegisters |> Map.toSeq)
      (* Extract only return registers *)
      |> Seq.filter (fun (regId, _) -> Set.contains regId returnRegisters)
      |> Seq.groupBy fst
      |> Seq.map (fun (regId, entries) ->
        regId, entries |> Seq.map snd |> Set.ofSeq)

    (* If debug history is enabled, Constraintorigins must be Some Map *)
    let trackOrigins = Option.isSome result.FinalState.Types.ConstraintOrigins

    (* Merge all ABI return registers from all RETURN leaf nodes *)
    let mergedConstraints, mergedOrigins, returnTidMap =
      mergeReturnTypeIds address name trackOrigins groupedReturnTypeIds

    (* Add new log for merged type constraint *)
    let constraintOrigins =
      match result.FinalState.Types.ConstraintOrigins, mergedOrigins with
      | Some origins, Some merged ->
        Some (
          Map.fold (fun acc key value -> Map.add key value acc) origins merged
        )
      | Some origins, None
      | None, Some origins -> Some origins
      | None, None -> None

    { Address = address
      Name = name
      Parameters = paramIdxTidMap
      Returns = returnTidMap
      Constraints = Set.union result.TypeConstraints mergedConstraints
      ConstraintOrigins = constraintOrigins
      NextTypeId = result.FinalState.Types.NextTypeId }
